LOCAL_DIR := $(GET_LOCAL_DIR)


# MAKEFILE FOR THE RGB DRIVER
MODULE := $(LOCAL_DIR).RGB

MODULE_NAME := GROVE-RGB-DRV

MODULE_TYPE = DRIVER

MODULE_SRCS := $(LOCAL_DIR)/GROVE-RGB.C

MODULE_STATIC_LIBS := SYSTEM/ULIB/DDK SYSTEM/ULIB/FIDL SYSTEM/ULIB/SYNC

MODULE_LIBS := SYSTEM/ULIB/DRIVER SYSTEM/ULIB/C SYSTEM/ULIB/ZIRCON

MODULE_BANJO_LIBS := SYSTEM/BANJO/DDK-PROTOCOL-I2C SYSTEM/BANJO/DDK-PROTOCOL-PLATFORM-DEVICE SYSTEM/BANJO/DDK-PROTOCOL-PLATFORM-BUS

MODULE_FIDL_LIBS := SYSTEM/FIDL/ZIRCON-DISPLAY-GROVE-RGB

INCLUDE MAKE/MODULE.MK


# MAKEFILE FOR THE LCD DRIVER
MODULE := $(LOCAL_DIR).LCD

MODULE_NAME := GROVE-LCD-DRV

MODULE_TYPE = DRIVER

MODULE_SRCS := $(LOCAL_DIR)/GROVE-LCD.C

MODULE_STATIC_LIBS := SYSTEM/ULIB/DDK SYSTEM/ULIB/FIDL SYSTEM/ULIB/SYNC

MODULE_LIBS := SYSTEM/ULIB/DRIVER SYSTEM/ULIB/C SYSTEM/ULIB/ZIRCON

MODULE_BANJO_LIBS := SYSTEM/BANJO/DDK-PROTOCOL-I2C SYSTEM/BANJO/DDK-PROTOCOL-PLATFORM-DEVICE SYSTEM/BANJO/DDK-PROTOCOL-PLATFORM-BUS

# MODULE_FIDL_LIBS := SYSTEM/FIDL/ZIRCON-DISPLAY-GROVE-LCD

include make/module.mk
